import type { Metadata } from "next";
import "./globals.css";
import Navbar from "../components/navbar/navbar";
import { ThemeProvider } from "@/provider/themeProvider";

export const metadata: Metadata = {
  title: "AR | Home",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
        >
          <Navbar />
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
